[workspace]
members = [
  "svd",
  "piece-1",
  "piece-2",
  "piece-3",
  "piece-4",
  "piece-5",
  "piece-6",
  "piece-7",
  "piece-8",
  "piece-9",
  "piece-10",
  "piece-11",
  "piece-12",
  "pieces",
  "res-gpio",
]

[package]
name = "drone-stm32-map"
version = "0.9.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
edition = "2018"
description = "Drone for STM32. Device mappings."
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/drone-os/drone-stm32-map"

[features]
default = []
stm32f100 = [
  "drone-stm32-map-pieces/stm32f100",
  "drone-stm32-map-res-gpio/stm32f100",
]
stm32f101 = [
  "drone-stm32-map-pieces/stm32f101",
  "drone-stm32-map-res-gpio/stm32f101",
]
stm32f102 = [
  "drone-stm32-map-pieces/stm32f102",
  "drone-stm32-map-res-gpio/stm32f102",
]
stm32f103 = [
  "drone-stm32-map-pieces/stm32f103",
  "drone-stm32-map-res-gpio/stm32f103",
]
stm32f107 = [
  "drone-stm32-map-pieces/stm32f107",
  "drone-stm32-map-res-gpio/stm32f107",
]
stm32l4x1 = [
  "drone-stm32-map-pieces/stm32l4x1",
  "drone-stm32-map-res-gpio/stm32l4x1",
]
stm32l4x2 = [
  "drone-stm32-map-pieces/stm32l4x2",
  "drone-stm32-map-res-gpio/stm32l4x2",
]
stm32l4x3 = [
  "drone-stm32-map-pieces/stm32l4x3",
  "drone-stm32-map-res-gpio/stm32l4x3",
]
stm32l4x5 = [
  "drone-stm32-map-pieces/stm32l4x5",
  "drone-stm32-map-res-gpio/stm32l4x5",
]
stm32l4x6 = [
  "drone-stm32-map-pieces/stm32l4x6",
  "drone-stm32-map-res-gpio/stm32l4x6",
]
stm32l4r5 = [
  "drone-stm32-map-pieces/stm32l4r5",
  "drone-stm32-map-res-gpio/stm32l4r5",
]
stm32l4r7 = [
  "drone-stm32-map-pieces/stm32l4r7",
  "drone-stm32-map-res-gpio/stm32l4r7",
]
stm32l4r9 = [
  "drone-stm32-map-pieces/stm32l4r9",
  "drone-stm32-map-res-gpio/stm32l4r9",
]
stm32l4s5 = [
  "drone-stm32-map-pieces/stm32l4s5",
  "drone-stm32-map-res-gpio/stm32l4s5",
]
stm32l4s7 = [
  "drone-stm32-map-pieces/stm32l4s7",
  "drone-stm32-map-res-gpio/stm32l4s7",
]
stm32l4s9 = [
  "drone-stm32-map-pieces/stm32l4s9",
  "drone-stm32-map-res-gpio/stm32l4s9",
]

[dependencies.drone-cortex-m]
version = "0.9.0"
git = "https://github.com/drone-os/drone-cortex-m"
# path = "../drone-cortex-m"

[dependencies.drone-stm32-map-pieces]
version = "=0.9.0"
path = "pieces"

[dependencies.drone-stm32-map-res-gpio]
version = "=0.9.0"
path = "res-gpio"
