[package]
name = "drone-stm32-map-pieces"
version = "0.9.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
edition = "2018"
repository = "https://github.com/drone-os/drone-stm32-map"
license = "MIT OR Apache-2.0"
description = """
STM32 peripheral mappings for Drone, an Embedded Operating System.
"""

[lib]
path = "lib.rs"

[features]
default = []
stm32f100 = [
    "drone-cortex-m/cortex_m3_r1p1",
    "drone-stm32-map-pieces-1/stm32f100",
    "drone-stm32-map-pieces-2/stm32f100",
    "drone-stm32-map-pieces-3/stm32f100",
    "drone-stm32-map-pieces-4/stm32f100",
    "drone-stm32-map-pieces-5/stm32f100",
    "drone-stm32-map-pieces-6/stm32f100",
    "drone-stm32-map-pieces-7/stm32f100",
    "drone-stm32-map-pieces-8/stm32f100",
    "drone-stm32-map-pieces-9/stm32f100",
    "drone-stm32-map-pieces-10/stm32f100",
    "drone-stm32-map-pieces-11/stm32f100",
    "drone-stm32-map-pieces-12/stm32f100",
]
stm32f101 = [
    "drone-cortex-m/cortex_m3_r1p1",
    "drone-stm32-map-pieces-1/stm32f101",
    "drone-stm32-map-pieces-2/stm32f101",
    "drone-stm32-map-pieces-3/stm32f101",
    "drone-stm32-map-pieces-4/stm32f101",
    "drone-stm32-map-pieces-5/stm32f101",
    "drone-stm32-map-pieces-6/stm32f101",
    "drone-stm32-map-pieces-7/stm32f101",
    "drone-stm32-map-pieces-8/stm32f101",
    "drone-stm32-map-pieces-9/stm32f101",
    "drone-stm32-map-pieces-10/stm32f101",
    "drone-stm32-map-pieces-11/stm32f101",
    "drone-stm32-map-pieces-12/stm32f101",
]
stm32f102 = [
    "drone-cortex-m/cortex_m3_r1p1",
    "drone-stm32-map-pieces-1/stm32f102",
    "drone-stm32-map-pieces-2/stm32f102",
    "drone-stm32-map-pieces-3/stm32f102",
    "drone-stm32-map-pieces-4/stm32f102",
    "drone-stm32-map-pieces-5/stm32f102",
    "drone-stm32-map-pieces-6/stm32f102",
    "drone-stm32-map-pieces-7/stm32f102",
    "drone-stm32-map-pieces-8/stm32f102",
    "drone-stm32-map-pieces-9/stm32f102",
    "drone-stm32-map-pieces-10/stm32f102",
    "drone-stm32-map-pieces-11/stm32f102",
    "drone-stm32-map-pieces-12/stm32f102",
]
stm32f103 = [
    "drone-cortex-m/cortex_m3_r1p1",
    "drone-stm32-map-pieces-1/stm32f103",
    "drone-stm32-map-pieces-2/stm32f103",
    "drone-stm32-map-pieces-3/stm32f103",
    "drone-stm32-map-pieces-4/stm32f103",
    "drone-stm32-map-pieces-5/stm32f103",
    "drone-stm32-map-pieces-6/stm32f103",
    "drone-stm32-map-pieces-7/stm32f103",
    "drone-stm32-map-pieces-8/stm32f103",
    "drone-stm32-map-pieces-9/stm32f103",
    "drone-stm32-map-pieces-10/stm32f103",
    "drone-stm32-map-pieces-11/stm32f103",
    "drone-stm32-map-pieces-12/stm32f103",
]
stm32f107 = [
    "drone-cortex-m/cortex_m3_r1p1",
    "drone-stm32-map-pieces-1/stm32f107",
    "drone-stm32-map-pieces-2/stm32f107",
    "drone-stm32-map-pieces-3/stm32f107",
    "drone-stm32-map-pieces-4/stm32f107",
    "drone-stm32-map-pieces-5/stm32f107",
    "drone-stm32-map-pieces-6/stm32f107",
    "drone-stm32-map-pieces-7/stm32f107",
    "drone-stm32-map-pieces-8/stm32f107",
    "drone-stm32-map-pieces-9/stm32f107",
    "drone-stm32-map-pieces-10/stm32f107",
    "drone-stm32-map-pieces-11/stm32f107",
    "drone-stm32-map-pieces-12/stm32f107",
]
stm32l4x1 = [
    "drone-cortex-m/cortex_m4f_r0p1",
    "drone-stm32-map-pieces-1/stm32l4x1",
    "drone-stm32-map-pieces-2/stm32l4x1",
    "drone-stm32-map-pieces-3/stm32l4x1",
    "drone-stm32-map-pieces-4/stm32l4x1",
    "drone-stm32-map-pieces-5/stm32l4x1",
    "drone-stm32-map-pieces-6/stm32l4x1",
    "drone-stm32-map-pieces-7/stm32l4x1",
    "drone-stm32-map-pieces-8/stm32l4x1",
    "drone-stm32-map-pieces-9/stm32l4x1",
    "drone-stm32-map-pieces-10/stm32l4x1",
    "drone-stm32-map-pieces-11/stm32l4x1",
    "drone-stm32-map-pieces-12/stm32l4x1",
]
stm32l4x2 = [
    "drone-cortex-m/cortex_m4f_r0p1",
    "drone-stm32-map-pieces-1/stm32l4x2",
    "drone-stm32-map-pieces-2/stm32l4x2",
    "drone-stm32-map-pieces-3/stm32l4x2",
    "drone-stm32-map-pieces-4/stm32l4x2",
    "drone-stm32-map-pieces-5/stm32l4x2",
    "drone-stm32-map-pieces-6/stm32l4x2",
    "drone-stm32-map-pieces-7/stm32l4x2",
    "drone-stm32-map-pieces-8/stm32l4x2",
    "drone-stm32-map-pieces-9/stm32l4x2",
    "drone-stm32-map-pieces-10/stm32l4x2",
    "drone-stm32-map-pieces-11/stm32l4x2",
    "drone-stm32-map-pieces-12/stm32l4x2",
]
stm32l4x3 = [
    "drone-cortex-m/cortex_m4f_r0p1",
    "drone-stm32-map-pieces-1/stm32l4x3",
    "drone-stm32-map-pieces-2/stm32l4x3",
    "drone-stm32-map-pieces-3/stm32l4x3",
    "drone-stm32-map-pieces-4/stm32l4x3",
    "drone-stm32-map-pieces-5/stm32l4x3",
    "drone-stm32-map-pieces-6/stm32l4x3",
    "drone-stm32-map-pieces-7/stm32l4x3",
    "drone-stm32-map-pieces-8/stm32l4x3",
    "drone-stm32-map-pieces-9/stm32l4x3",
    "drone-stm32-map-pieces-10/stm32l4x3",
    "drone-stm32-map-pieces-11/stm32l4x3",
    "drone-stm32-map-pieces-12/stm32l4x3",
]
stm32l4x5 = [
    "drone-cortex-m/cortex_m4f_r0p1",
    "drone-stm32-map-pieces-1/stm32l4x5",
    "drone-stm32-map-pieces-2/stm32l4x5",
    "drone-stm32-map-pieces-3/stm32l4x5",
    "drone-stm32-map-pieces-4/stm32l4x5",
    "drone-stm32-map-pieces-5/stm32l4x5",
    "drone-stm32-map-pieces-6/stm32l4x5",
    "drone-stm32-map-pieces-7/stm32l4x5",
    "drone-stm32-map-pieces-8/stm32l4x5",
    "drone-stm32-map-pieces-9/stm32l4x5",
    "drone-stm32-map-pieces-10/stm32l4x5",
    "drone-stm32-map-pieces-11/stm32l4x5",
    "drone-stm32-map-pieces-12/stm32l4x5",
]
stm32l4x6 = [
    "drone-cortex-m/cortex_m4f_r0p1",
    "drone-stm32-map-pieces-1/stm32l4x6",
    "drone-stm32-map-pieces-2/stm32l4x6",
    "drone-stm32-map-pieces-3/stm32l4x6",
    "drone-stm32-map-pieces-4/stm32l4x6",
    "drone-stm32-map-pieces-5/stm32l4x6",
    "drone-stm32-map-pieces-6/stm32l4x6",
    "drone-stm32-map-pieces-7/stm32l4x6",
    "drone-stm32-map-pieces-8/stm32l4x6",
    "drone-stm32-map-pieces-9/stm32l4x6",
    "drone-stm32-map-pieces-10/stm32l4x6",
    "drone-stm32-map-pieces-11/stm32l4x6",
    "drone-stm32-map-pieces-12/stm32l4x6",
]
stm32l4r5 = [
    "drone-cortex-m/cortex_m4f_r0p1",
    "drone-stm32-map-pieces-1/stm32l4r5",
    "drone-stm32-map-pieces-2/stm32l4r5",
    "drone-stm32-map-pieces-3/stm32l4r5",
    "drone-stm32-map-pieces-4/stm32l4r5",
    "drone-stm32-map-pieces-5/stm32l4r5",
    "drone-stm32-map-pieces-6/stm32l4r5",
    "drone-stm32-map-pieces-7/stm32l4r5",
    "drone-stm32-map-pieces-8/stm32l4r5",
    "drone-stm32-map-pieces-9/stm32l4r5",
    "drone-stm32-map-pieces-10/stm32l4r5",
    "drone-stm32-map-pieces-11/stm32l4r5",
    "drone-stm32-map-pieces-12/stm32l4r5",
]
stm32l4r7 = [
    "drone-cortex-m/cortex_m4f_r0p1",
    "drone-stm32-map-pieces-1/stm32l4r7",
    "drone-stm32-map-pieces-2/stm32l4r7",
    "drone-stm32-map-pieces-3/stm32l4r7",
    "drone-stm32-map-pieces-4/stm32l4r7",
    "drone-stm32-map-pieces-5/stm32l4r7",
    "drone-stm32-map-pieces-6/stm32l4r7",
    "drone-stm32-map-pieces-7/stm32l4r7",
    "drone-stm32-map-pieces-8/stm32l4r7",
    "drone-stm32-map-pieces-9/stm32l4r7",
    "drone-stm32-map-pieces-10/stm32l4r7",
    "drone-stm32-map-pieces-11/stm32l4r7",
    "drone-stm32-map-pieces-12/stm32l4r7",
]
stm32l4r9 = [
    "drone-cortex-m/cortex_m4f_r0p1",
    "drone-stm32-map-pieces-1/stm32l4r9",
    "drone-stm32-map-pieces-2/stm32l4r9",
    "drone-stm32-map-pieces-3/stm32l4r9",
    "drone-stm32-map-pieces-4/stm32l4r9",
    "drone-stm32-map-pieces-5/stm32l4r9",
    "drone-stm32-map-pieces-6/stm32l4r9",
    "drone-stm32-map-pieces-7/stm32l4r9",
    "drone-stm32-map-pieces-8/stm32l4r9",
    "drone-stm32-map-pieces-9/stm32l4r9",
    "drone-stm32-map-pieces-10/stm32l4r9",
    "drone-stm32-map-pieces-11/stm32l4r9",
    "drone-stm32-map-pieces-12/stm32l4r9",
]
stm32l4s5 = [
    "drone-cortex-m/cortex_m4f_r0p1",
    "drone-stm32-map-pieces-1/stm32l4s5",
    "drone-stm32-map-pieces-2/stm32l4s5",
    "drone-stm32-map-pieces-3/stm32l4s5",
    "drone-stm32-map-pieces-4/stm32l4s5",
    "drone-stm32-map-pieces-5/stm32l4s5",
    "drone-stm32-map-pieces-6/stm32l4s5",
    "drone-stm32-map-pieces-7/stm32l4s5",
    "drone-stm32-map-pieces-8/stm32l4s5",
    "drone-stm32-map-pieces-9/stm32l4s5",
    "drone-stm32-map-pieces-10/stm32l4s5",
    "drone-stm32-map-pieces-11/stm32l4s5",
    "drone-stm32-map-pieces-12/stm32l4s5",
]
stm32l4s7 = [
    "drone-cortex-m/cortex_m4f_r0p1",
    "drone-stm32-map-pieces-1/stm32l4s7",
    "drone-stm32-map-pieces-2/stm32l4s7",
    "drone-stm32-map-pieces-3/stm32l4s7",
    "drone-stm32-map-pieces-4/stm32l4s7",
    "drone-stm32-map-pieces-5/stm32l4s7",
    "drone-stm32-map-pieces-6/stm32l4s7",
    "drone-stm32-map-pieces-7/stm32l4s7",
    "drone-stm32-map-pieces-8/stm32l4s7",
    "drone-stm32-map-pieces-9/stm32l4s7",
    "drone-stm32-map-pieces-10/stm32l4s7",
    "drone-stm32-map-pieces-11/stm32l4s7",
    "drone-stm32-map-pieces-12/stm32l4s7",
]
stm32l4s9 = [
    "drone-cortex-m/cortex_m4f_r0p1",
    "drone-stm32-map-pieces-1/stm32l4s9",
    "drone-stm32-map-pieces-2/stm32l4s9",
    "drone-stm32-map-pieces-3/stm32l4s9",
    "drone-stm32-map-pieces-4/stm32l4s9",
    "drone-stm32-map-pieces-5/stm32l4s9",
    "drone-stm32-map-pieces-6/stm32l4s9",
    "drone-stm32-map-pieces-7/stm32l4s9",
    "drone-stm32-map-pieces-8/stm32l4s9",
    "drone-stm32-map-pieces-9/stm32l4s9",
    "drone-stm32-map-pieces-10/stm32l4s9",
    "drone-stm32-map-pieces-11/stm32l4s9",
    "drone-stm32-map-pieces-12/stm32l4s9",
]

[dependencies.drone-core]
version = "0.9.0"
path = "../../../drone-core"

[dependencies.drone-cortex-m]
version = "0.9.0"
path = "../../../drone-cortex-m"

[dependencies.drone-stm32-map-pieces-1]
version = "=0.9.0"
path = "1"

[dependencies.drone-stm32-map-pieces-2]
version = "=0.9.0"
path = "2"

[dependencies.drone-stm32-map-pieces-3]
version = "=0.9.0"
path = "3"

[dependencies.drone-stm32-map-pieces-4]
version = "=0.9.0"
path = "4"

[dependencies.drone-stm32-map-pieces-5]
version = "=0.9.0"
path = "5"

[dependencies.drone-stm32-map-pieces-6]
version = "=0.9.0"
path = "6"

[dependencies.drone-stm32-map-pieces-7]
version = "=0.9.0"
path = "7"

[dependencies.drone-stm32-map-pieces-8]
version = "=0.9.0"
path = "8"

[dependencies.drone-stm32-map-pieces-9]
version = "=0.9.0"
path = "9"

[dependencies.drone-stm32-map-pieces-10]
version = "=0.9.0"
path = "10"

[dependencies.drone-stm32-map-pieces-11]
version = "=0.9.0"
path = "11"

[dependencies.drone-stm32-map-pieces-12]
version = "=0.9.0"
path = "12"

[build-dependencies.drone-stm32-map-svd]
version = "=0.9.0"
path = "../../svd"
