[package]
name = "drone-stm32-map-svd"
version = "0.10.1"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
edition = "2018"
repository = "https://github.com/drone-os/drone-stm32-map"
homepage = "https://www.drone-os.com/"
documentation = "https://api.drone-os.com/drone-stm32-map/0.10/drone_stm32_map_svd/"
license = "MIT OR Apache-2.0"
description = """
STM32 SVD to Drone bindings converter.
"""

[dependencies]
failure = "0.1"
serde = {version = "1", features = ["derive"]}
serde-xml-rs = "0.2"
