[package]
name = "drone-stm32-map-svd"
version = "0.9.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
edition = "2018"
description = "Drone for STM32 bindings generator."
license = "MIT OR Apache-2.0"
repository = "https://github.com/drone-os/drone-stm32-map"

[dependencies]
serde = {version = "1", features = ["derive"]}
serde-xml-rs = "0.2"
failure = "0.1"
